### ISSUE TITLE
-UseBasicParsing

### ISSUE THREAD

**Issue by bwdur** [simonxciv/Bamboozled#1]
Hey!  Thanks so much for your little wrapper.  I found a small little issue and I'm too lazy to do a fork/pull request for it.  I was scheduling a script that uses this and running it under a service account, and got this error:

```
Invoke-WebRequest : The response content cannot be parsed because the Internet Explorer engine is not available, or
Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again.
At C:\Scripts\Modules\Bamboozled\Bamboozled.psm1:91 char:30
+ ... Directory = Invoke-WebRequest $directoryUrl -method POST -Credential  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (:) [Invoke-WebRequest], NotSupportedException
    + FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Microsoft.PowerShell.Commands.InvokeWebRequestComman
   d

```
A quick google showed that you can add the -UseBasicParsing switch to Invoke-WebRequest if the user can't launch IE, and that seemed to worked just fine!

**Comment by simonxciv** [comment]
Hi @bwdur this looks good to me. I've merged your PR now.

**Comment by bwdur** [comment]
Honestly I was about to do what you're doing but you beat me to it!  When I
get back to work this week I'll see if I can contribute more.

**Comment by simonxciv** [comment]
I'm glad you found it helpful. Anything you feel like contributing would mean a lot. At the moment I've got a small list of things to work on. When I get a minute, I'll open some issues so that you can see what I'm doing. Feel free to raise issues for anything you'd like to see done.

In the meantime, I added a [new repo](https://github.com/simonxciv/Bamboozled-Update-Active-Directory) with a script that uses this module if you're interested. It's pretty basic, but you might find it helpful.

**Comment by bwdur** [comment]
Thanks.  That is pretty similar to what I'm doing!  Just finished adding,
updating, and removing ad users based on bamboohr data.  I have users in
different distribution groups based on a custom field in Bamboo that I just
need to update on change correctly.  Almost done!

By the way the custom fields are just prefixed with custom in the API, like
customEmailGroup is my custom Email Group field.  It took me a bit to find
that info.
